spring:
  thymeleaf:
    mode: HTML
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_blog?useUnicode=true&characterEncoding=utf-8
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.whf: info
  file:
    name: log/my_blog.log

server:
  port: 8080
